export const overlayLocator = {
  body: 'html[lang="ko"]>body',
  dimmed: 'div#dimmedOverlay',
  insOverlay: "//div[contains(@class, 'ins-custom-overlay')]",
  insCloseButton: "//div[contains(@class, 'ins-close-button') and text()='닫기']",
  content: 'div.modal-content',
  header: 'header.modal-header',
  bodyContent: 'div.modal-body',
  closeButton: 'div.modal-content button.c-btn-close',
  title: '*[class="modal-title"]',
  closeContainer: '.share_pop_cont',
  closeX: '.ui_modal_close',
  modal: 'div.modal-content',
  checkbox: 'div.modal-body input[type=checkbox]',
  button: 'div.modal-content button',
  buttonIns: 'div.ins-content-wrapper a[id*="ins-editable-button"]',
  footerButton: 'div.modal-content footer button',
};

export const appMenuLocator = {
  gnbList: 'ul.header-gnb-list',
  mainMenu: '.c-btn-menu',
  expandAll: 'button.dep_all',
  backHistory: 'button.history_back',
  previousPage: '.c-btn-prev',
  nextButton: "//android.widget.Button[@text='다음']",
  allow: 'com.android.permissioncontroller:id/permission_allow_button',
  allowAll: 'com.android.permissioncontroller:id/permission_allow_all_button',
  allowForegroundOnly:
    'com.android.permissioncontroller:id/permission_allow_foreground_only_button',
  agree: 'com.lguplus.mobile.cs:id/agreeButton',
  enterWithoutLoginText: "//android.widget.Button[@text='로그인하지 않고 입장할게요']",
  enterWithoutLogin: "//android.widget.Button[@text='로그인없이 입장하기']",
  closeButtonText: "//android.widget.Button[@text='닫기']",
  withoutLoginWeb: "button[class='withoutLogin']",
};

export const modalLocator = {
  modalContent: '.modal-content',
  modalCheckbox: '#modal-checkbox',
  modalCloseButton: '.modal-close',
  modalActionButton: '.modal-action',
  modalInsButton: '.modal-ins',
  dimmedLayer: '.dimmed',
  addressInput: '#address-search-input',
  addressSearchButton: '#address-search-btn',
  confirmButton: 'div.c-btn-group button.c-btn-solid-1-m',
  eventModalClose: '.event-modal-close',
  marketPopupClose: '.market-popup-close',
};
