export const urls = {
  lg: {
    main: 'https://m.lguplus.com/main',
    search: 'https://m.lguplus.com/search/result?searchWord=로밍&category=indv',
    gnb: 'https://m.lguplus.com/gnb',
    mobilePlan: 'https://m.lguplus.com/mobile/plan/mplan/5g-all',
    mobile: 'https://m.lguplus.com/mobile',
    internetIptv: 'https://m.lguplus.com/internet-iptv',
    benefits: 'https://m.lguplus.com/benefit',
    support: 'https://m.lguplus.com/support',
    direct: 'https://m.lguplus.com/direct',
    roaming: 'https://m.lguplus.com/plan/roaming/?p=1',
  },
  skt: {
    main: 'https://m.tworld.co.kr/v6/my?returnUrl=https://m.tworld.co.kr/v6/menu',
    search: 'https://m.tworld.co.kr/common/search?q=고객센터',
    gnb: 'https://m.tworld.co.kr/v6/menu',
    mobilePlan: 'https://m.tworld.co.kr/product/renewal/mobileplan/list?filters=F01713',
    mobile: 'https://m.shop.tworld.co.kr/shop/main?referrer=undefined',
    internetIptv: 'https://m.shop.tworld.co.kr/wire/main',
    benefits: 'https://m.tworld.co.kr/membership/submain',
    support: 'https://m.tworld.co.kr/customer',
    direct: 'https://m.shop.tworld.co.kr/buyproc/omd/usim-opening',
    roaming: 'https://m.tworld.co.kr/product/roaming',
  },
  kt: {
    main: 'https://m.kt.com/',
    search: 'https://m.search.kt.com/?c=MOL000000&r=10&ch=USR000&k=출석체크',
    gnb: '',
    mobilePlan: 'https://m.product.kt.com/mDic/index.do?CateCode=6041',
    mobile: 'https://m.shop.kt.com/m/main.do',
    internetIptv: 'https://m.shop.kt.com:444/m/unify/wireProdbestCombi.do',
    benefits: 'https://m.membership.kt.com/main/s_MainInfo.do',
    support: 'https://m.help.kt.com/s_main.jsp',
    direct: 'https://m.shop.kt.com:444/m/direct/directUsim.do',
    roaming: 'https://m.globalroaming.kt.com/main.asp',
  },
};
